// Generated by scripts/gen-config.ts from @rome-protocol/registry (+ deployed addresses). Committed on
// purpose so API functions never depend on build order. Public data only. Do not edit by hand.
export interface IndexedNetwork {
  chainId: number;
  chainName: string;
  network: string;
  proxyUrl: string;
  vault: string | null;
  wusdc: string;
}
export const NETWORKS: IndexedNetwork[] = [
  {
    "chainId": 200010,
    "chainName": "Rome Hadrian",
    "network": "devnet",
    "proxyUrl": "https://hadrian.testnet.romeprotocol.xyz/",
    "vault": "0xaec0b79a84f985d0f91099c70892ae3e8f777fca",
    "wusdc": "0xd4cc34b67c805d472b5a709a22a1037f6b16ef28"
  },
  {
    "chainId": 121214,
    "chainName": "Rome Martius",
    "network": "testnet",
    "proxyUrl": "https://martius.testnet.romeprotocol.xyz/",
    "vault": null,
    "wusdc": "0x2fffdfa11a9cef9210dc34e975649f09119c4efb"
  }
];
